meals/urls.py
from django.urls import path
from . import views



app_name = 'meals'

urlpatterns = [
    path('',views.meal_list , name='meal_list' ),
    path('<slug:slug>' , views.meal_detail , name='meal_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('meals/' , include('meals.urls' , namespace='meals')),
    path('blog/' , include('blog.urls' , namespace='blog')),
    path('contact/' , include('contact.urls' , namespace='contact')),
    path('about-us/' , include('aboutus.urls' , namespace='aboutus')),
    path('reserve_table/' , include('reservation.urls' , namespace='reservation')),
    path('' , include('home.urls' , namespace='home')),
    path('qr/', include('qr.urls' , namespace='qr')),
    path('register/', include('register.urls' , namespace='register')),
    path('login/', include('login.urls' , namespace='login')),
    path('logout/', include('logout.urls' , namespace='logout')),
    
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Resturant AdminPanel"
admin.site.site_title = "Resturant App Admin "
admin.site.site_index_title = "Welcome To Resturant Admin Panel"

qr/urls.py
from django.urls import path
from . import views

app_name = 'qr'

urlpatterns = [
    path('',views.qr_list , name='qr_list' ),
]

meals/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.


class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category' , on_delete=models.SET_NULL , null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5 , decimal_places=2)
    preperation_time =models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)
    


    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Meals , self).save(*args , **kwargs)



    class Meta:
        verbose_name = 'platillo'
        verbose_name_plural = 'platillos'


    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=30)


    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.name

meals/views.py
from django.shortcuts import render

# Create your views here.
from .models import Meals , Category

def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()

    context = {
        'meal_list' : meal_list ,
        'categories' : categories ,
    }

    return render(request , 'Meals/list.html' , context)



def meal_detail(request , slug):
    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail' : meal_detail}

    return render(request , 'Meals/detail.html' , context)

meals/templates/Meals/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  

  
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});
          height: 70vh;" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up" align="center">
                  <h2 class="heading">Informacion sobre el platillo
                  </h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                    <img class="meal_img" src="{{meal_detail.image.url}}" alt="">
                    <h2>{{meal_detail}}</h2>
                    <p>{{meal_detail.description}}</p>

                    <p>Para :{{meal_detail.people}} Personas</p>
                    <p>Tiempo en prepararse : {{meal_detail.preperation_time}} Minutos</p>
                    <p>Precio : ${{meal_detail.price}} </p>

              </div>
            </div>
          </div>
        </div>


        

      </div> <!-- .main-wrap -->
      
      {% endblock body %}

meals/templates/Meals/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  

  
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});
          height: 70vh;" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up" align="center">
                  <h2 class="heading">En este apartado podras encontrar toda la informacion correspondiente a nuestro menu
                  </h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                  {% for category in categories %}
                    <li class="nav-item">
                      <a class="nav-link " id="{{category}}-tab" data-toggle="pill" href="#{{category}}" role="tab" aria-controls="{{category}}" aria-selected="true">{{category}}</a>
                    </li>
                  {% endfor %}

                </ul>


                <div class="tab-content" id="pills-tabContent">

                  {% for category in categories %}

                    <div class="tab-pane fade show" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">
                      
                      {% for meal in meal_list %}
                          {% if meal.category == category%}
                            <div class="d-block d-md-flex menu-food-item">
                              <div class="text order-1 mb-3">
                                <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h3>
                                <p>{{meal.description}}</p>
                              </div>
                              <div class="price order-2">
                                <strong>${{meal.price}}</strong>
                              </div>
                            </div> <!-- .menu-food-item -->
                          {% endif %}
                      {% endfor %}

                    </div>
                    
                  {% endfor %}
                </div>


              </div>
            </div>
          </div>
        </div>


        

      </div> <!-- .main-wrap -->
      
      {% endblock body %}